### PR TITLE
remove SIX

### PR DESCRIPTION
**Pull request by a-detiste**
https://wiki.debian.org/Python3-six-removal

### CODE REVIEW

**Comment by bennylope** [comment]
This would be great! Getting rid of `six` is arguably one of the biggest chores in this project right now.

_Unfortunately_ simply removing it like in ace42a1cfb190bdf3d9c7865d5b1a1f392b90353 isn't enough 😞, there's also some work required to update the "metaclass orchestration" https://github.com/bennylope/django-organizations/actions/runs/6787974831/job/18501285489?pr=255#step:5:44

**Comment by a-detiste** [comment]
Ok, part of why I do this is to learn better python3, here clearly don't understand enough of the mater.

**Comment by bennylope** [comment]
@a-detiste that's okay! I sincerely appreciate that you took the effort to tackle the issue.

**Comment by a-detiste** [comment]
I will bookmark your changes to see if they also applie to other six-using django packages:
```
python3-django-dynamic-preferences       2     
python3-django-pglocks                   3     
python3-django-yarnpkg                   3     
python3-django-dbbackup                  7     
python3-django-etcd-settings             7     
python3-django-session-security          7     
python3-django-auto-one-to-one           8     
python3-scrapy-djangoitem                8     
python3-django-bitfield                  9     
python3-django-netfields                 9     
python3-django-shortuuidfield            10    
python3-django-organizations             11    
python3-django-ordered-model             13    
python3-django-cas-server                14    
python3-django-maintenancemode           14    
python3-django-oauth-toolkit             14    
python3-django-wkhtmltopdf               16    
python3-django-environ                   31    
python3-django-horizon                   35    
python3-django-pyscss                    44    
python3-django-q                         138   
python3-django-picklefield               142   
python3-django-compressor                183   
python3-django-guardian                  202   
python3-django-appconf                   357 
```

**Comment by bennylope** [comment]
All I did was extract from `six` the function that combined the metaclasses, for what it's worth. Whether it's the "best" method is was certainly the most expedient.

**Pull request closed without merging**
